export interface GalleryPhoto {
  id: string;
  src: string;
  title: string;
  category: "Match" | "Training" | "Trophy" | "Event";
  description: string;
  aspect: string;
  type?: "image" | "video";
  poster?: string;
}

export const GALLERY_PHOTOS: GalleryPhoto[] = [

  // ─── Practice / Training ─────────────────────────────────────────────────────
  {
    id: "practice-1",
    src: "/practice/WhatsApp Image 2026-06-23 at 1.19.50 PM.jpeg",
    title: "U17 7-a-Side Tournament",
    category: "Match",
    description: "U17 7-a-side tournament at Bhopal.",
    aspect: "aspect-video",
    type: "image",
  },
  {
    id: "practice-2",
    src: "/practice/WhatsApp Image 2026-06-25 at 11.48.06 PM.jpeg",
    title: "Evening Training",
    category: "Training",
    description: "Evening training session at Bade Ground — players giving their best.",
    aspect: "aspect-[4/3]",
    type: "image",
  },
  {
    id: "practice-3",
    src: "/practice/WhatsApp Image 2026-06-25 at 11.48.07 PM.jpeg",
    title: "On the Ground",
    category: "Training",
    description: "Practice underway at Bade Ground, Mandideep.",
    aspect: "aspect-square",
    type: "image",
  },
  {
    id: "practice-4",
    src: "/practice/WhatsApp Image 2026-06-25 at 11.48.08 PM (1).jpeg",
    title: "Team Practice",
    category: "Training",
    description: "Regular evening practice session at Bade Ground.",
    aspect: "aspect-[3/4]",
    type: "image",
  },
  {
    id: "practice-5",
    src: "/practice/WhatsApp Image 2026-06-25 at 11.48.08 PM (2).jpeg",
    title: "Ground Session",
    category: "Training",
    description: "Players working hard during practice at Bade Ground, Mandideep.",
    aspect: "aspect-video",
    type: "image",
  },
  {
    id: "practice-6",
    src: "/practice/WhatsApp Image 2026-06-25 at 11.48.08 PM (3).jpeg",
    title: "Squad Training",
    category: "Training",
    description: "Full squad in action during a practice session at Bade Ground.",
    aspect: "aspect-[4/3]",
    type: "image",
  },
  {
    id: "practice-7",
    src: "/practice/WhatsApp Image 2026-06-25 at 11.48.08 PM (4).jpeg",
    title: "Practice Drills",
    category: "Training",
    description: "Drills and exercises at Bade Ground during an evening session.",
    aspect: "aspect-square",
    type: "image",
  },
  {
    id: "practice-8",
    src: "/practice/WhatsApp Image 2026-06-25 at 11.48.08 PM (5).jpeg",
    title: "Training at Bade Ground",
    category: "Training",
    description: "Players training together at Bade Ground, Mandideep.",
    aspect: "aspect-[3/2]",
    type: "image",
  },
  {
    id: "practice-9",
    src: "/practice/WhatsApp Image 2026-06-25 at 11.48.08 PM (6).jpeg",
    title: "Club Session",
    category: "Training",
    description: "Club practice session in the evening at Bade Ground.",
    aspect: "aspect-video",
    type: "image",
  },
  {
    id: "practice-10",
    src: "/practice/WhatsApp Image 2026-06-25 at 11.48.08 PM.jpeg",
    title: "Practice Time",
    category: "Training",
    description: "Practice time at Bade Ground, Mandideep — building skills every day.",
    aspect: "aspect-[4/3]",
    type: "image",
  },
  {
    id: "trials-1",
    src: "/practice/WhatsApp Image 2026-06-26 at 12.18.15 AM.jpeg",
    title: "Player Trials",
    category: "Training",
    description: "Trials session at Bade Ground — evening, open to all.",
    aspect: "aspect-video",
    type: "image",
  },

  // ─── Match ───────────────────────────────────────────────────────────────────
  {
    id: "u20-1",
    src: "/practice/WhatsApp Image 2026-06-26 at 12.18.15 AM (1).jpeg",
    title: "U20 Team — Indore",
    category: "Match",
    description: "U20 squad ready before the game at Indore.",
    aspect: "aspect-video",
    type: "image",
  },
  {
    id: "match-school-1",
    src: "/practice/WhatsApp Image 2026-06-26 at 12.18.19 AM.jpeg",
    title: "School Tournament",
    category: "Match",
    description: "Inter-school football tournament — teams lined up before kick-off.",
    aspect: "aspect-video",
    type: "image",
  },
  {
    id: "match-away-1",
    src: "/practice/WhatsApp Image 2026-06-26 at 12.18.20 AM.jpeg",
    title: "Away Game",
    category: "Match",
    description: "Players heading out for an away fixture.",
    aspect: "aspect-[3/4]",
    type: "image",
  },

  // ─── Events ──────────────────────────────────────────────────────────────────
  {
    id: "summer-camp-1",
    src: "/practice/WhatsApp Image 2026-06-26 at 12.18.14 AM.jpeg",
    title: "Summer Camp 2025",
    category: "Event",
    description: "Summer Camp at Bade Ground — 10 May to 15 June 2025, 5 PM to 7:30 PM.",
    aspect: "aspect-square",
    type: "image",
  },
  {
    id: "holi-poster-1",
    src: "/practice/WhatsApp Image 2026-06-26 at 12.18.15 AM (2).jpeg",
    title: "Holi 2025",
    category: "Event",
    description: "Vindhyachal FC wishes everyone a colourful Holi.",
    aspect: "aspect-[3/4]",
    type: "image",
  },
  {
    id: "holi-celebration-1",
    src: "/practice/WhatsApp Image 2026-06-26 at 12.18.15 AM (3).jpeg",
    title: "Holi Celebration",
    category: "Event",
    description: "Club members celebrating Holi together at night.",
    aspect: "aspect-[3/4]",
    type: "image",
  },
  {
    id: "khel-mahakumbh-1",
    src: "/practice/WhatsApp Image 2026-06-26 at 12.18.16 AM.jpeg",
    title: "Khel Mahakumbh",
    category: "Event",
    description: "Team at the Khel Mahakumbh event — January 2026.",
    aspect: "aspect-video",
    type: "image",
  },
  {
    id: "diwali-rangoli-1",
    src: "/practice/WhatsApp Image 2026-06-26 at 12.18.17 AM.jpeg",
    title: "Diwali at the Ground",
    category: "Event",
    description: "Diwali celebration at Bade Ground — diyas and rangoli.",
    aspect: "aspect-square",
    type: "image",
  },
  {
    id: "diwali-poster-1",
    src: "/practice/WhatsApp Image 2026-06-26 at 12.18.18 AM.jpeg",
    title: "Happy Diwali",
    category: "Event",
    description: "Vindhyachal Football Club wishes everyone a Happy Diwali.",
    aspect: "aspect-[3/4]",
    type: "image",
  },

  // ─── Videos ──────────────────────────────────────────────────────────────────
  {
    id: "video-1",
    src: "/practice/WhatsApp Video 2026-06-25 at 11.48.08 PM.mp4",
    poster: "/practice/WhatsApp Image 2026-06-25 at 11.48.08 PM (2).jpeg",
    title: "Practice Session",
    category: "Training",
    description: "Practice session at Bade Ground, Mandideep.",
    aspect: "aspect-video",
    type: "video",
  },
  {
    id: "video-2",
    src: "/practice/WhatsApp Video 2026-06-26 at 12.18.14 AM.mp4",
    poster: "/practice/WhatsApp Image 2026-06-26 at 12.18.15 AM (1).jpeg",
    title: "Match Highlights",
    category: "Match",
    description: "Highlights from the U20 Indore game.",
    aspect: "aspect-video",
    type: "video",
  },
];
